name: Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: extract_version
        run: |
          if [[ $GITHUB_REF =~ refs/tags/v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
            VERSION=${BASH_REMATCH[0]}
            echo "VERSION=$VERSION" >> $GITHUB_ENV
          else
            echo "No version found in tag"
            exit 1
        continue-on-error: true

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/twinejs-docker:latest
            ghcr.io/${{ github.repository_owner }}/twinejs-docker:${{ env.VERSION || 'latest' }}